"""Registry-backed visibility for operational diagnostic CLI surfaces."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Literal

RecordScope = Literal["none", "diagnostic_run"]


@dataclass(frozen=True)
class DiagnosticInventoryEntry:
    """Operational shape declaration for one diagnostic/test-like CLI surface."""

    name: str
    cli_flags: tuple[str, ...]
    uses_projected_state: bool
    uses_repo_files: bool
    supports_json: bool
    supports_record: bool
    record_scope: RecordScope
    emits_diagnostic_facts: bool
    emits_cluster_facts: bool
    writes_event_ledger: bool
    mutates_cluster: bool
    reads_diagnostic_facts: bool
    description: str

    def to_json_dict(self) -> dict[str, object]:
        data = asdict(self)
        data["cli_flags"] = list(self.cli_flags)
        return data


DIAGNOSTIC_INVENTORY: tuple[DiagnosticInventoryEntry, ...] = (
    DiagnosticInventoryEntry(
        name="classification_coverage",
        cli_flags=("--classification-coverage",),
        uses_projected_state=True,
        uses_repo_files=False,
        supports_json=False,
        supports_record=True,
        record_scope="diagnostic_run",
        emits_diagnostic_facts=True,
        emits_cluster_facts=False,
        writes_event_ledger=True,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Reports projected entity classification coverage and unknown contributors.",
    ),
    DiagnosticInventoryEntry(
        name="graph_issue_summary",
        cli_flags=("--graph-issue-summary",),
        uses_projected_state=True,
        uses_repo_files=False,
        supports_json=False,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Reports grouped projected graph validation issues.",
    ),
    DiagnosticInventoryEntry(
        name="knowledge_reachability",
        cli_flags=(
            "--knowledge-reachability-audit",
            "--knowledge-reachability-audit-json",
        ),
        uses_projected_state=True,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Audits knowledge reachability across projected, repository, inquiry, and rendered surfaces.",
    ),
    DiagnosticInventoryEntry(
        name="documentation_structure",
        cli_flags=("--documentation-structure",),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Observes structural metadata for top-level repository Markdown docs without interpreting prose, extracting claims, inferring authority, inferring shapes, writing events, or mutating the repository.",
    ),
    DiagnosticInventoryEntry(
        name="ownership_discrepancies",
        cli_flags=("--ownership-discrepancies",),
        uses_projected_state=True,
        uses_repo_files=False,
        supports_json=True,
        supports_record=True,
        record_scope="diagnostic_run",
        emits_diagnostic_facts=True,
        emits_cluster_facts=False,
        writes_event_ledger=True,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Reports storage/service ownership candidates, conflicts, and capability needs.",
    ),
    DiagnosticInventoryEntry(
        name="audit_snapshot",
        cli_flags=("--audit-snapshot",),
        uses_projected_state=True,
        uses_repo_files=False,
        supports_json=False,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Saves local operational audit output and best-effort git metadata under .audit/seed/ without recording facts.",
    ),
    DiagnosticInventoryEntry(
        name="audit_snapshots",
        cli_flags=("--audit-snapshots",),
        uses_projected_state=False,
        uses_repo_files=False,
        supports_json=False,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Lists local operational audit snapshot artifacts from .audit/seed/.",
    ),
    DiagnosticInventoryEntry(
        name="audit_compare",
        cli_flags=("--audit-compare",),
        uses_projected_state=False,
        uses_repo_files=False,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Compares two local operational audit snapshots without recording facts.",
    ),
    DiagnosticInventoryEntry(
        name="operational_surface_inventory",
        cli_flags=("--operational-surface-inventory",),
        uses_projected_state=False,
        uses_repo_files=False,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Discovers operational CLI surfaces from argparse implementation evidence without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="visibility_coverage_audit",
        cli_flags=("--visibility-coverage-audit",),
        uses_projected_state=False,
        uses_repo_files=False,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Compares implementation-discovered operational surfaces with diagnostic inventory visibility without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="operational_surface_classification_audit",
        cli_flags=("--operational-surface-classification-audit",),
        uses_projected_state=False,
        uses_repo_files=False,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Classifies discovered CLI elements into primary surfaces, filters, modifiers, debug, manual-input, legacy, or unknown without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="consumer_audit",
        cli_flags=("--consumer-audit",),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Audits implementation-backed consumers of observation predicates and diagnostic surfaces without recording facts.",
    ),
    DiagnosticInventoryEntry(
        name="emitter_consumer_audit",
        cli_flags=("--emitter-consumer-audit", "--include-rendered"),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Audits implementation-backed emitted outputs and their visible consumers without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="emitter_attribution_audit",
        cli_flags=("--emitter-attribution-audit", "--include-rendered"),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Explains attributed, dynamic, indirect, discovery-gap, missing, or unknown emitter attribution without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="component_audit",
        cli_flags=("--component-audit",),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Summarizes a named component role from repository, graph, consumer, test, and architecture evidence without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="architecture_conformance_audit",
        cli_flags=("--architecture-conformance-audit",),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Compares architecture evidence with observed operational structure, significance breakdowns, and concept realizations without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="operational_graph",
        cli_flags=("--operational-graph",),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Builds a read-only implementation-backed operational relationship graph with evidence and confidence without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="operational_graph_taxonomy",
        cli_flags=("--operational-graph-taxonomy",),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Summarizes operational graph node classifications and aggregate connectivity without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="operational_graph_confidence",
        cli_flags=("--operational-graph-confidence", "--exclude-aggregate"),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Analyzes operational graph edge confidence reasons, evidence categories, representative examples, and important weak relationships without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="observation_utilization",
        cli_flags=("--observation-utilization",),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description=(
            "Audits implementation source participation of observation predicates "
            "across projection, read-model, and diagnostic surfaces without "
            "loading projected state."
        ),
    ),
    DiagnosticInventoryEntry(
        name="observation_domains",
        cli_flags=("--observation-domains",),
        uses_projected_state=True,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=True,
        description="Shows read-only observation-domain coverage and gap classification from existing observation, capability, and operational evidence without recording or mutation.",
    ),
    DiagnosticInventoryEntry(
        name="capability_needs",
        cli_flags=("--capability-needs",),
        uses_projected_state=True,
        uses_repo_files=False,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=True,
        description="Reads recorded diagnostic facts and reports capability needs by subject.",
    ),
    DiagnosticInventoryEntry(
        name="capability_relationship",
        cli_flags=("--capability-relationship",),
        uses_projected_state=True,
        uses_repo_files=False,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=True,
        description="Explains read-only capability relationship context across access, benefit, pressure, attainability, expectation, and unknowns without acquisition, policy, planning, recording, event ledger writes, or cluster mutation.",
    ),
    DiagnosticInventoryEntry(
        name="investigation_path",
        cli_flags=("--investigation-path",),
        uses_projected_state=False,
        uses_repo_files=False,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Exposes evidence-backed read-only investigation paths across existing diagnostic surfaces without planning, recording, event ledger writes, or cluster mutation.",
    ),
    DiagnosticInventoryEntry(
        name="reasoning_path",
        cli_flags=("--reasoning-path",),
        uses_projected_state=True,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=True,
        description="Exposes evidence-backed derivation paths from source evidence through conclusions, consumers, and story impact without recording facts, event ledger writes, or cluster mutation.",
    ),
    DiagnosticInventoryEntry(
        name="selection_path",
        cli_flags=("--selection-path",),
        uses_projected_state=True,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=True,
        description="Exposes read-only implementation-backed selection paths showing candidates, factors, non-selected alternatives, and outcome without recording facts, event ledger writes, or cluster mutation.",
    ),
    DiagnosticInventoryEntry(
        name="operational_story",
        cli_flags=("--operational-story",),
        uses_projected_state=True,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=True,
        description="Composes existing operational evidence into a read-only story view without recording facts, event ledger writes, or cluster mutation.",
    ),
    DiagnosticInventoryEntry(
        name="ops_brief",
        cli_flags=("--ops-brief",),
        uses_projected_state=True,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=True,
        description="Aggregates existing operational visibility surfaces into a read-only triage brief.",
    ),
    DiagnosticInventoryEntry(
        name="current_facts_cache_debug",
        cli_flags=("--current-facts-cache-debug",),
        uses_projected_state=True,
        uses_repo_files=False,
        supports_json=False,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Reports read-only current-facts cache and timing phases without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="impact_audit",
        cli_flags=("--impact-audit",),
        uses_projected_state=False,
        uses_repo_files=False,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Compares existing operational audit snapshots, reports snapshot coverage, and classifies observable outcome impact without recording facts.",
    ),
    DiagnosticInventoryEntry(
        name="history_brief",
        cli_flags=("--history-brief",),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Synthesizes existing impact, snapshot-policy, and repository-state visibility into a read-only historical brief without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="reference_selection",
        cli_flags=("--reference-selection",),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Exposes read-only implementation-selected comparison-reference visibility for a question domain without recording facts, event ledger writes, baseline creation, expectations, or cluster mutation.",
    ),
    DiagnosticInventoryEntry(
        name="repository_state_observation",
        cli_flags=("--observe-repository",),
        uses_projected_state=False,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Observes read-only repository state for an arbitrary local repository path without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="snapshot_policy_audit",
        cli_flags=("--snapshot-policy-audit",),
        uses_projected_state=False,
        uses_repo_files=False,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Audits snapshot readiness, comparison availability, and visibility recommendations without creating snapshots, writing events, or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="pressure_audit",
        cli_flags=("--pressure-audit",),
        uses_projected_state=True,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=True,
        description="Ranks operational pressure from existing visibility surfaces without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="correlation_audit",
        cli_flags=("--correlation-audit",),
        uses_projected_state=True,
        uses_repo_files=True,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=True,
        description="Correlates existing evidence, consumers, and pressure surfaces to expose suspected operational disconnects without recording facts.",
    ),
    DiagnosticInventoryEntry(
        name="projection_shape",
        cli_flags=("--projection-shape",),
        uses_projected_state=False,
        uses_repo_files=False,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Shows read-only implementation-backed projection stage shape without recording facts or mutating cluster state.",
    ),
    DiagnosticInventoryEntry(
        name="inquiry_artifacts",
        cli_flags=("--inquiry-artifacts",),
        uses_projected_state=False,
        uses_repo_files=False,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=False,
        description="Shows read-only repository-visible inquiry artifact classifications without recording, event-ledger writes, cluster mutation, inquiry graph creation, pressure transformation inference, workflow, or planning behavior.",
    ),
    DiagnosticInventoryEntry(
        name="privilege_discovery",
        cli_flags=("--privilege-discovery",),
        uses_projected_state=True,
        uses_repo_files=False,
        supports_json=True,
        supports_record=False,
        record_scope="none",
        emits_diagnostic_facts=False,
        emits_cluster_facts=False,
        writes_event_ledger=False,
        mutates_cluster=False,
        reads_diagnostic_facts=True,
        description="Explains privilege boundaries for current capability needs without privileged actions, fact recording, or cluster mutation.",
    ),
)


def diagnostic_inventory_json(
    entries: tuple[DiagnosticInventoryEntry, ...] = DIAGNOSTIC_INVENTORY,
) -> list[dict[str, object]]:
    return [entry.to_json_dict() for entry in entries]


def format_diagnostic_inventory(
    entries: tuple[DiagnosticInventoryEntry, ...] = DIAGNOSTIC_INVENTORY,
) -> str:
    headers = [
        "Diagnostic",
        "CLI Flag",
        "Uses State",
        "Uses Repo Files",
        "JSON",
        "Record",
        "Record Scope",
        "Emits Facts",
        "Mutates Cluster",
        "Notes",
    ]
    rows = [
        [
            entry.name,
            ", ".join(entry.cli_flags),
            _yes_no(entry.uses_projected_state),
            _yes_no(entry.uses_repo_files),
            _yes_no(entry.supports_json),
            _yes_no(entry.supports_record),
            entry.record_scope,
            _emits_facts_label(entry),
            _yes_no(entry.mutates_cluster),
            _notes(entry),
        ]
        for entry in entries
    ]
    widths = [
        max(len(row[index]) for row in [headers, *rows])
        for index in range(len(headers))
    ]
    rendered = [_render_row(headers, widths)]
    rendered.extend(_render_row(row, widths) for row in rows)
    return "\n".join(rendered)


def _render_row(row: list[str], widths: list[int]) -> str:
    return " | ".join(value.ljust(widths[index]) for index, value in enumerate(row))


def _yes_no(value: bool) -> str:
    return "yes" if value else "no"


def _emits_facts_label(entry: DiagnosticInventoryEntry) -> str:
    if entry.emits_diagnostic_facts and entry.emits_cluster_facts:
        return "diagnostic and cluster facts"
    if entry.emits_diagnostic_facts:
        return "diagnostic facts"
    if entry.emits_cluster_facts:
        return "cluster facts"
    return "no"


def _notes(entry: DiagnosticInventoryEntry) -> str:
    notes = [entry.description]
    if entry.supports_record:
        notes.append("recorded subjects use diagnostic_run:<id>")
    if entry.writes_event_ledger:
        notes.append("writes_event_ledger=true")
    if entry.reads_diagnostic_facts:
        notes.append("reads_diagnostic_facts=true")
    return " ".join(notes)
